import type { Metadata } from "next";
import RootLayoutComponent from "@/components/Layout/Root";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <RootLayoutComponent>{children}</RootLayoutComponent>;
}
